pipeline:
  backend:
    image: haskell:8.4.4
    group: build
    commands:
      - apt-get update
      - apt-get install libpq-dev
      - cd backend/
      - stack build --test --copy-bins
      - cp /root/.local/bin/main main
      - tar -cvf out.tar main Dockerfile
    volumes:
      - '/tmp/cache_stack/snapshots:/root/.stack/snapshots'

  frontend:
    image: node:dubnium
    group: build
    environment:
      - 'API_URL=https://advance-wars-maybe-backend.raymond-h.me'
      - 'AUTH0_DOMAIN=advance-wars-maybe.eu.auth0.com'
      - 'AUTH0_REDIRECT_URI=https://game-thing-maybe.netlify.com/login_callback'
      - 'AUTH0_AUDIENCE=https://advance-wars-maybe-backend.raymond-h.me/'
      - 'AUTH0_LOGOUT_URL=https://game-thing-maybe.netlify.com/'
      - 'PUSHER_APP_KEY=c95114659ae51046d6c6'
      - 'PUSHER_CLUSTER=eu'
    secrets: [ auth0_client_id ]
    commands:
      - cd frontend/
      - npm install
      - npm run lint
      - npm test
      - npm run build
      - cp -R static/* dist/

  deploy-backend:
    image: ebiwd/alpine-ssh
    group: deploy
    secrets: [ dokku_key ]
    commands:
      - 'add-ssh-key dokku "$DOKKU_KEY"'
      - 'ssh dokku@raymond-h.me -- tar:in advance-wars-maybe-backend < backend/out.tar'
    when:
      event: push
      branch: master

  deploy-frontend:
    image: lucap/drone-netlify
    group: deploy
    secrets: [ netlify_token ]
    site_id: 36abb268-dd0b-49f4-aa53-559c5eb22ecf
    path: frontend/dist
    when:
      event: push
      branch: master
