pipeline:
  backend:
    image: haskell:8.4.4
    commands:
      - cd backend/
      - stack test
      - stack build
      - stack install
      - cp /root/.local/bin/main main
      - tar -cvf out.tar main Dockerfile
    volumes:
      - '/tmp/cache_stack:/root/.stack'
