pipeline:
  backend:
    image: haskell:8.4.4
    commands:
      - cd backend/
      - stack test
      - stack build
      - stack install
      - cp /root/.local/bin/main main
      - tar -cvf out.tar main Dockerfile
    volumes:
      - '/tmp/cache_stack/snapshots:/root/.stack/snapshots'

  deploy-backend:
    image: ebiwd/alpine-ssh
    secrets: [ dokku_key ]
    commands:
      - 'add-ssh-key dokku "$DOKKU_KEY"'
      - 'ssh dokku@raymond-h.me -- tar:in advance-wars-maybe-backend < backend/out.tar'
