name: backend
version: 0.1.0.0
# github: "githubuser/scotty-hspec-wai"
license: BSD3
author: "Raymond Hammarling"
# maintainer: "example@example.com"
copyright: "2018 Raymond Hammarling"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description: Please see the README on GitHub at <https://github.com/githubuser/scotty-hspec-wai#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- stm
- dotenv
- time
- lens
- bytestring
- wai
- wai-extra
- http-types
- scotty
- aeson
- lens-aeson
- jose
- mtl
- wreq
- text
- base64-bytestring
- base16-bytestring
- wai-cors
- either

library:
  source-dirs: src

executables:
  main:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend

tests:
  backend-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
